### ISSUE TITLE
♪♫ Everything is broken, everything is broken ♪♫

### ISSUE THREAD

**Issue by adrienbrunet** [beautifuldjango/beautifuldjango.github.io#11]
@ewjoachim haaaaalp

Website does not load the css anymore. 😢 
You move `css/main.scss` to `assets/main.scss` ??
And... it's broken. I reverted it. Still broken.

Plz, jekyll god, have mercy. Here is an offering 🐱

**Comment by adrienbrunet** [comment]
My offering thing worked.

**Comment by adrienbrunet** [comment]
(I edited the config file, back to normal, plz ignore my crazyness 🙈 )

Love you all ❤️

**Comment by ewjoachim** [comment]
Oo Sorry about the mess. I can't understand why it does this.

**Comment by ewjoachim** [comment]
There's something awfully disturbing in the fact the same Jekyll version processing the same website needs a same file to be located at 2 different locations respectively in order for it to work on github.io and locally. I'll try to see. Sorry again 🙇 😭

**Comment by adrienbrunet** [comment]
At least now, I have a procedure to fix it.
1-mess around random files
2-cat emoji offering to jekyll god
3-ask for help you don't need 'cause jekyll God is now listening to you
4-let jekyll god do god stuff

And it's fixed.

If you can find why we have this strange behavior... =)

**Comment by ewjoachim** [comment]
And here's the whole of it:

minima, the default theme was installed at a different version from the one used on GH. Versions used on GH are [listed here](https://pages.github.com/versions/). They're automatically maintained in a package that was supposed to be used in the Gemfile if I had [RTFM](https://github.com/beautifuldjango/beautifuldjango.github.io/blob/dfc53a23bcf0b63cf6ec121173eb151cb6dc0554/Gemfile#L20-L22).

So now I'm properly installing everything with bundle install with no sudo gem install, and it's quite better.

This is the minima install message : 

```
Post-install message from minima:

----------------------------------------------
Thank you for installing minima 2.0!

Minima 2.0 comes with a breaking change that
renders '<your-site>/css/main.scss' redundant.
That file is now bundled with this gem as
'<minima>/assets/main.scss'.

More Information:
https://github.com/jekyll/minima#customization
----------------------------------------------
```
