### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ewjoachim** [beautifuldjango/beautifuldjango.github.io#14]
You've indicated in the GH project that the license is CC-BY-SA, which is displayed on the main project page (upper right corner), but in reality, it's a CC-SA. Which one is the right one ?

**Comment by adrienbrunet** [comment]
It's a trap. 🚲 

updated.

**Comment by ewjoachim** [comment]
Updated ? I still see CC-BY-SA on GitHub...?

<img width="1008" alt="capture d ecran 2016-10-22 a 22 57 59" src="https://cloud.githubusercontent.com/assets/1457576/19622481/04c73a14-98ab-11e6-9c8d-233b2b2b3c0e.png">

**Comment by adrienbrunet** [comment]
CC-SA makes no sens. It's CC-BY-SA. I've updated the license section.

**Comment by ewjoachim** [comment]
Oh, I didn't know you cannot use "Share alike" without "attribution". I'm not sure why, but indeed it's what the CC website says. Ok then.
