### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by adrienbrunet** [beautifuldjango/beautifuldjango.github.io#15]
Context: A friend of mine is going to help us illustrate the book! We should have logo proposals soon. It does not necessarily implies we're going to change the actual one. We will probably keep it as a title and have another one as an illustration.

Meanwhile, can we get rid of the dot above the "j" @ewjoachim ? I think it would better without it.

I'm waiting for some drawings that I'll share with you and we will able to make some decisions. =) Stay tuned!

**Comment by ewjoachim** [comment]
Aw, I like that dot, it was our "unique" part, the only touch of originality in our logo :cry: 

Just kidding, I'll do it. :+1:
