### ISSUE TITLE
Theme update

### ISSUE THREAD

**Issue by adrienbrunet** [beautifuldjango/beautifuldjango.github.io#16]
@ewjoachim You proposed [this theme](https://github.com/mmistakes/minimal-mistakes) and some stock photos as a starting point. I thought about it, that's really better than our actual theme which isn't really appropriate. We should do it before DUTH.

I'm heading to Berlin and won't be able to commit a lot during the entire week to come. WOuld you like to do it? I'm going to try to do it myself if you can't. But time is running out 🕐 

You can use the pictures you proposed me as a baseline (books photos or abstract pictures). Once we get some drawings from our designer... We'll see how to use them properly.

**Comment by ewjoachim** [comment]
You got it !

**Comment by ewjoachim** [comment]
https://www.youtube.com/watch?v=zhAmug6Ts6o
